trigger:
- main  # or the branch you want to trigger on

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    python -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
    pip install pytest
  displayName: 'Install dependencies'

- script: |
    source venv/bin/activate
    python -m pytest tests/
  displayName: 'Run tests'

- script: |
    source venv/bin/activate
    python app.py
  displayName: 'Run Flask App'
