trigger:
- main

pool:
  name: Default

steps:
- script: |
    # Commands to build the Flask app
    cd $(Build.SourcesDirectory)

  displayName: 'Build Flask App'

- task: Docker@2
  inputs:
    containerRegistry: 'FrostlineDevopsDockerHub'  # Use Docker Hub service connection
    repository: 'frostlinegamesdocker/flaskapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
  displayName: 'Dockerize and Push'

- script: |
    # Commands to run the Docker container
    docker run -d -p 8080:5000 frostlinegamesdocker/flaskapp:$(Build.BuildId)
  displayName: 'Run Docker Container'
