trigger:
- main

pool:
  name: Default

steps:
- script: |
    # Commands to build the Flask app
    cd $(Build.SourcesDirectory)
    # Build your Flask app here
    sudo usermod -aG docker $USER
  displayName: 'Build Flask App'

- script: |
    sudo docker build -t frostlinegamesdocker/flaskapp:$(Build.BuildId) .
    sudo docker push frostlinegamesdocker/flaskapp:$(Build.BuildId)
  displayName: 'Dockerize and Push'

- script: |
    # Commands to run the Docker container
    docker run -d -p 8080:5000 frostlinegamesdocker/flaskapp:$(Build.BuildId)
  displayName: 'Run Docker Container'
