
trigger:
- main  # or the branch you want to trigger on

pool:
  name: 'Default'  # Specify the label of your self-hosted Windows agent

steps:
- script: |
    hostname
  displayName: 'Display Hostname'

- script: |
    C:\Users\frost\AppData\Local\Programs\Python\Python312 -m venv venv
    venv\Scripts\activate
    C:\Users\frost\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    venv\Scripts\activate
    python app.py
  displayName: 'Run Flask App'
